### ISSUE TITLE
Align query logic with expectations

### ISSUE THREAD

**Issue by phackstock** [iiasa/pysquirrel#12]
When using a query such as:

```
>>> pysquirrel.nuts.get(country_code="BE", level=[1, 2, 3])
```

I'd expect to get all NUTS regions for Belgium.
Currently we'd get nothing since the filter is an AND and there's no country codes with levels 1,2 and 3.

**Comment by dc-almeida** [comment]
Of the five fields, country_code and level seem to have the most immediate use cases and are easy to implement with an AND logic (and in the process, simplify the code).
Should I drop the remaining ones for now?

**Comment by phackstock** [comment]
I'd say so, making sure to keep it simple is always a good idea.
