### ISSUE TITLE
Turn Region.parent_code into a property

### ISSUE THREAD

**Issue by phackstock** [iiasa/pysquirrel#18]
I would turn `Region.parent_code` into an property. The reason for that is that all the information to get the parent_code is already contained in the class.
The property would then look like this:

```python
@property
def parent_code(self) -> str | None:
    return self.code[:-1] if self.level > 1 else None
```

this would also make the `_load` function shorter and easier to read.

**Comment by dc-almeida** [comment]
Was also considering doing a forward reference, make the parent attribute the same region class and that way the functionality of parent searching is imbedded in the class itself

**Comment by phackstock** [comment]
Ah yes, that would be a nice idea too. I'm not sure we'd need that functionality. \
Don't let that stop you ff you want to implement it though.
