### ISSUE TITLE
Use and enforce auto formatting tools

### ISSUE THREAD

**Issue by phackstock** [iiasa/pysquirrel#7]
I would suggest using [black](https://pypi.org/project/black/) as the code formatting tool. 
This would apply to both using it locally on your machine to format the code as well as setting up a GitHub action to check if any PR is black compliant.

**Comment by meksor** [comment]
fyi as far as i can see ixmp4, scse-spatial, scse-files and scse-processing all switched to `ruff` over `black`

**Comment by phackstock** [comment]
Good point @meksor, we've also switched to ruff for pyam. Probably good to continue the trend here.
